document: feedback-pipeline-workload
version: 1
data:
  name: agenda
  description: Fedora com.github.dahenson.agenda flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - agenda
