document: feedback-pipeline-workload
version: 1
data:
  name: amarok
  description: Fedora org.kde.amarok flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - amarok
    - audiocd-kio
