document: feedback-pipeline-workload
version: 1
data:
  name: crow-translate
  description: Fedora org.kde.CrowTranslate flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - crow-translate
