document: feedback-pipeline-workload
version: 1
data:
  name: deja-dup
  description: Fedora org.gnome.DejaDup flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - deja-dup
    # optional dependencies
    - restic
