document: feedback-pipeline-workload
version: 1
data:
  name: dragon
  description: Fedora org.kde.dragonplayer flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - dragon
