document: feedback-pipeline-workload
version: 1
data:
  name: extremetuxracer
  description: Fedora net.sourceforge.extremetuxracer flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - extremetuxracer
