document: feedback-pipeline-workload
version: 1
data:
  name: flatpak-kde5-runtime
  description: Fedora org.fedoraproject.KDE5Platform flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde5-runtime
  packages:
    - abattis-cantarell-vf-fonts
    - acl
    - adwaita-cursor-theme
    - adwaita-icon-theme
    - adwaita-icon-theme-legacy
    - alsa-lib
    - alsa-plugins-arcamav
    - alsa-plugins-oss
    - alsa-plugins-pulseaudio
    - alsa-plugins-upmix
    - alsa-plugins-usbstream
    - alsa-plugins-vdownmix
    - alternatives
    - appstream
    - aribb24
    - assimp
    - at-spi2-atk
    - at-spi2-core
    - atk
    - attr
    - audit-libs
    - authselect
    - authselect-libs
    - avahi-glib
    - avahi-libs
    - bash
    - bash-completion
    - bluez-libs
    - breeze-icon-theme
    - breeze-icon-theme-rcc
    - bsdcat
    - bsdcpio
    - bsdtar
    - bsdunzip
    - bubblewrap
    - bzip2
    - bzip2-libs
    - ca-certificates
    - cairo
    - cairo-gobject
    - cdparanoia-libs
    - cjson
    - cmake-filesystem
    - codec2
    - colord-libs
    - coreutils-single
    - cracklib
    - cracklib-dicts
    - crypto-policies
    - cups-client
    - cups-filesystem
    - cups-libs
    - curl
    - cyrus-sasl-gssapi
    - cyrus-sasl-lib
    - cyrus-sasl-md5
    - cyrus-sasl-plain
    - cyrus-sasl-scram
    - dbus
    - dbus-common
    - dbus-libs
    - dbus-tools
    - dbusmenu-qt5
    - default-fonts-core-sans
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - desktop-file-utils
    - diffutils
    - dns-root-data
    - docbook-dtds
    - docbook-style-xsl
    - double-conversion
    - duktape
    - e2fsprogs-libs
    - ebook-tools-libs
    - editorconfig-libs
    - elfutils-debuginfod-client
    - elfutils-default-yama-scope
    - elfutils-libelf
    - elfutils-libs
    - emacs-filesystem
    - exiv2-libs
    - expat
    - faad2-libs
    - fcitx5-gtk
    - fcitx5-gtk3
    - fcitx5-qt-libfcitx5qtdbus
    - fcitx5-qt5
    - fdk-aac-free
    - fedora-gpg-keys
    - fedora-logos
    - fedora-release-common
    - fedora-release-flatpak
    - fedora-release-identity-flatpak
    - fedora-repos
    - ffmpeg-free
    - fftw-libs-double
    - fftw-libs-single
    - file
    - file-libs
    - filesystem
    - findutils
    - flac
    - flac-libs
    - flatpak-runtime-config
    - flatpak-spawn
    - flatpak-xdg-utils
    - flite
    - fmt
    - fontconfig
    - fonts-filesystem
    - freeglut
    - freetype
    - frei0r-plugins
    - fribidi
    - game-music-emu
    - gavl
    - gawk
    - gdbm-libs
    - gdk-pixbuf2
    - geoclue2-libs
    - gettext
    - gettext-envsubst
    - gettext-libs
    - gettext-runtime
    - giflib
    - glib-networking
    - glib2
    - glibc
    - glibc-common
    - glibc-gconv-extra
    - glibc-langpack-*
    - glibc-minimal-langpack
    - glx-utils
    - glycin-libs
    - glycin-loaders
    - gmp
    - gmp-c++
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - gnupg2
    - gnupg2-dirmngr
    - gnupg2-gpg-agent
    - gnupg2-gpgconf
    - gnupg2-keyboxd
    - gnupg2-scdaemon
    - gnupg2-smime
    - gnupg2-utils
    - gnupg2-verify
    - gnupg2-wks
    - gnutls
    - gnutls-c++
    - gnutls-dane
    - gnutls-utils
    - gobject-introspection
    - google-carlito-fonts
    - google-crosextra-caladea-fonts
    - google-noto-color-emoji-fonts
    - google-noto-fonts-common
    - google-noto-sans-mono-vf-fonts
    - google-noto-sans-vf-fonts
    - google-noto-serif-vf-fonts
    - gpgme
    - gpgmepp
    - graphene
    - graphite2
    - grep
    - gsettings-desktop-schemas
    - gsm
    - gssdp
    - gstreamer1
    - gstreamer1-plugin-dav1d
    - gstreamer1-plugin-gif
    - gstreamer1-plugin-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-libs
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-gtk
    - gstreamer1-plugins-good-qt
    - gtk-immodules-imsettings
    - gtk-update-icon-cache
    - gtk3
    - gtk3-immodule-xim
    - gtk3-immodules
    - gupnp
    - gupnp-igd
    - gzip
    - harfbuzz
    - harfbuzz-icu
    - hicolor-icon-theme
    - highway
    - hiredis
    - hostname
    - hunspell
    - hunspell-??
    - hunspell-??-*
    - hunspell-???
    - hunspell-en-US
    - hunspell-filesystem
    - hwdata
    - hyphen
    - hyphen-??
    - hyphen-??-*
    - hyphen-???
    - ibus-gtk3
    - ibus-libs
    - ilbc
    - imath
    - inih
    - inih-cpp
    - iso-codes
    - jansson
    - jasper-libs
    - jbigkit-libs
    - json-c
    - json-glib
    - kaccounts-integration-qt5
    - kde-filesystem
    - kde-settings
    - kdsoap
    - keyutils-libs
    - kf5-attica
    - kf5-bluez-qt
    - kf5-filesystem
    - kf5-frameworkintegration
    - kf5-frameworkintegration-libs
    - kf5-kactivities
    - kf5-kactivities-stats
    - kf5-karchive
    - kf5-kauth
    - kf5-kbookmarks
    - kf5-kcalendarcore
    - kf5-kcmutils
    - kf5-kcodecs
    - kf5-kcompletion
    - kf5-kconfig-core
    - kf5-kconfig-gui
    - kf5-kconfigwidgets
    - kf5-kcontacts
    - kf5-kcoreaddons
    - kf5-kcrash
    - kf5-kdav
    - kf5-kdbusaddons
    - kf5-kdeclarative
    - kf5-kded
    - kf5-kdesignerplugin
    - kf5-kdnssd
    - kf5-kdoctools
    - kf5-kemoticons
    - kf5-kfilemetadata
    - kf5-kglobalaccel
    - kf5-kglobalaccel-libs
    - kf5-kguiaddons
    - kf5-kholidays
    - kf5-ki18n
    - kf5-kiconthemes
    - kf5-kidletime
    - kf5-kimageformats
    - kf5-kinit
    - kf5-kio-core
    - kf5-kio-core-libs
    - kf5-kio-doc
    - kf5-kio-file-widgets
    - kf5-kio-gui
    - kf5-kio-ntlm
    - kf5-kio-widgets
    - kf5-kio-widgets-libs
    - kf5-kirigami2
    - kf5-kirigami2-addons
    - kf5-kitemmodels
    - kf5-kitemviews
    - kf5-kjobwidgets
    - kf5-knewstuff
    - kf5-knotifications
    - kf5-knotifyconfig
    - kf5-kpackage
    - kf5-kparts
    - kf5-kplotting
    - kf5-kpty
    - kf5-kquickcharts
    - kf5-kservice
    - kf5-ktexteditor
    - kf5-ktextwidgets
    - kf5-kunitconversion
    - kf5-kwallet
    - kf5-kwallet-libs
    - kf5-kwayland
    - kf5-kwidgetsaddons
    - kf5-kwindowsystem
    - kf5-kxmlgui
    - kf5-kxmlrpcclient
    - kf5-plasma
    - kf5-prison
    - kf5-purpose
    - kf5-qqc2-breeze-style
    - kf5-qqc2-desktop-style
    - kf5-solid
    - kf5-sonnet
    - kf5-sonnet-core
    - kf5-sonnet-hunspell
    - kf5-sonnet-ui
    - kf5-syndication
    - kf5-syntax-highlighting
    - kf5-threadweaver
    - kio-extras-kf5
    - krb5-libs
    - kwayland-integration
    - ladspa
    - lame
    - lame-libs
    - lcms2
    - leptonica
    - less
    - libaccounts-glib
    - libaccounts-qt5
    - libacl
    - libaom
    - libappstream-glib
    - libarchive
    - libaribcaption
    - libasan
    - libass
    - libassuan
    - libasyncns
    - libatomic
    - libattr
    - libavc1394
    - libavcodec-free
    - libavdevice-free
    - libavfilter-free
    - libavformat-free
    - libavif
    - libavutil-free
    - libblkid
    - libbluray
    - libbrotli
    - libbs2b
    - libcaca
    - libcanberra
    - libcap
    - libcap-ng
    - libcbor
    - libcdio
    - libcdio-paranoia
    - libchromaprint
    - libcloudproviders
    - libcom_err
    - libcurl
    - libdatrie
    - libdav1d
    - libdc1394
    - libdecor
    - libdeflate
    - libdmtx
    - libdovi
    - libdrm
    - libdvbv5
    - libdvdnav
    - libdvdread
    - libebur128
    - libeconf
    - libedit
    - libepoxy
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - libevdev
    - libevent
    - libexif
    - libfdisk
    - libffi
    - libfido2
    - libfl2
    - libfontenc
    - libfyaml
    - libgcab1
    - libgcc
    - libgcrypt
    - libgdither
    - libgfortran
    - libglvnd
    - libglvnd-egl
    - libglvnd-gles
    - libglvnd-glx
    - libglvnd-opengl
    - libgomp
    - libgpg-error
    - libgudev
    - libgusb
    - libheif
    - libical
    - libICE
    - libicu
    - libidn2
    - libiec61883
    - libimobiledevice
    - libimobiledevice-glue
    - libinput
    - libitm
    - libjpeg-turbo
    - libjpeg-turbo-utils
    - libjxl
    - libkexiv2-qt5
    - libksba
    - liblastlog2
    - liblc3
    - libldac
    - libldb
    - liblerc
    - liblsan
    - libmng
    - libmodplug
    - libmount
    - libmtp
    - libmysofa
    - libnghttp2
    - libnice
    - libnice-gstreamer1
    - libnotify
    - libnsl2
    - libobjc
    - libogg
    - libopenjph
    - libopenmpt
    - libpciaccess
    - libpkgconf
    - libplacebo
    - libplist
    - libpng
    - libpostproc-free
    - libproxy
    - libpsl
    - librabbitmq
    - LibRaw
    - libraw1394
    - librist
    - librsvg2
    - libsamplerate
    - libsbc
    - libseccomp
    - libsecret
    - libselinux
    - libsemanage
    - libsepol
    - libshaderc
    - libshout
    - libSM
    - libsmartcols
    - libsmbclient
    - libsndfile
    - libsodium
    - libsoup3
    - libsrtp
    - libss
    - libssh
    - libssh-config
    - libstdc++
    - libstemmer
    - libswresample-free
    - libswscale-free
    - libtalloc
    - libtasn1
    - libtdb
    - libtevent
    - libtextstyle
    - libthai
    - libtheora
    - libtiff
    - libtinysparql
    - libtirpc
    - libtommath
    - libtool-ltdl
    - libtsan
    - libubsan
    - libudfread
    - libunibreak
    - libunistring
    - libunwind
    - libusb1
    - libusbmuxd
    - libutempter
    - libuuid
    - libv4l
    - libva
    - libvdpau
    - libverto
    - libvisual
    - libvorbis
    - libvpx
    - libwacom
    - libwacom-data
    - libwayland-client
    - libwayland-cursor
    - libwayland-egl
    - libwayland-server
    - libwbclient
    - libwebp
    - libwebp-tools
    - libX11
    - libX11-common
    - libX11-xcb
    - libXau
    - libxcb
    - libXcomposite
    - libxcrypt
    - libXcursor
    - libXdamage
    - libXdmcp
    - libXext
    - libXfixes
    - libXft
    - libXi
    - libXinerama
    - libxkbcommon
    - libxkbcommon-x11
    - libxkbfile
    - libxml2
    - libxmlb
    - libXpm
    - libXrandr
    - libXrender
    - libXScrnSaver
    - libxshmfence
    - libxslt
    - libXtst
    - libXv
    - libXxf86vm
    - libyaml
    - libyuv
    - libzip
    - libzstd
    - lilv-libs
    - lmdb-libs
    - lpcnetfreedv
    - lua
    - lua-libs
    - lz4
    - lz4-libs
    - lzip
    - lzo
    - mailcap
    - mbedtls
    - mesa-filesystem
    - mesa-libgbm
    - mesa-libGLU
    - mkfontscale
    - mpdecimal
    - mpfr
    - mpg123-libs
    - mtdev
    - mythes
    - mythes-??
    - mythes-??-*
    - nano
    - ncompress
    - ncurses
    - ncurses-base
    - ncurses-libs
    - ncurses-term
    - nettle
    - ngtcp2
    - ngtcp2-crypto-gnutls
    - ngtcp2-crypto-ossl
    - noopenh264
    - npth
    - nspr
    - nss
    - nss-mdns
    - nss-softokn
    - nss-softokn-freebl
    - nss-sysinit
    - nss-util
    - nss_db
    - nss_hesiod
    - openal-soft
    - opencl-filesystem
    - OpenCL-ICD-Loader
    - opencore-amr
    - openexr-libs
    - openjpeg
    - openjpeg-tools
    - openldap
    - openpgm
    - openssh
    - openssh-clients
    - openssl-libs
    - opus
    - opusfile
    - orc
    - p11-kit
    - p11-kit-client
    - p11-kit-trust
    - pam-libs
    - pango
    - pciutils-libs
    - pcre2
    - pcre2-syntax
    - pcre2-utf16
    - pcre2-utf32
    - phonon-common
    - phonon-qt5
    - phonon-qt5-backend-gstreamer
    - pipewire-alsa
    - pipewire-gstreamer
    - pipewire-jack-audio-connection-kit
    - pipewire-jack-audio-connection-kit-libs
    - pipewire-libs
    - pixman
    - pkcs11-provider
    - pkgconf
    - pkgconf-m4
    - pkgconf-pkg-config
    - plasma-breeze-common
    - plasma-breeze-qt5
    - plasma-integration-qt5
    - plutosvg
    - plutovg
    - polkit-libs
    - polkit-qt5-1
    - poly2tri
    - poppler
    - poppler-data
    - poppler-glib
    - poppler-qt5
    - popt
    - procps-ng
    - protobuf-c
    - publicsuffix-list-dafsa
    - pugixml
    - pulseaudio-libs
    - pulseaudio-libs-glib2
    - python-pip-wheel
    - python-qt5-rpm-macros
    - python-unversioned-command
    - python3
    - python3-brotli
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-gobject-base
    - python3-gpg
    - python3-libs
    - python3-libxml2
    - python3-libxslt
    - python3-mako
    - python3-markdown
    - python3-markupsafe
    - python3-packaging
    - python3-pyqt5-sip
    - python3-qt5
    - python3-qt5-base
    - python3-setuptools
    - python3-six
    - python3-tkinter
    - qadwaitadecorations-qt5
    - qca-qt5
    - qca-qt5-cyrus-sasl
    - qca-qt5-gnupg
    - qca-qt5-logger
    - qca-qt5-nss
    - qca-qt5-ossl
    - qca-qt5-softstore
    - qgpgme-qt5
    - qrencode-libs
    - qt-settings
    - qt5-filesystem
    - qt5-qt3d
    - qt5-qtbase
    - qt5-qtbase-common
    - qt5-qtbase-gui
    - qt5-qtcharts
    - qt5-qtconnectivity
    - qt5-qtdeclarative
    - qt5-qtgamepad
    - qt5-qtgraphicaleffects
    - qt5-qtimageformats
    - qt5-qtlocation
    - qt5-qtmultimedia
    - qt5-qtnetworkauth
    - qt5-qtquickcontrols
    - qt5-qtquickcontrols2
    - qt5-qtremoteobjects
    - qt5-qtscript
    - qt5-qtsensors
    - qt5-qtserialport
    - qt5-qtspeech
    - qt5-qtspeech-flite
    - qt5-qtspeech-speechd
    - qt5-qtsvg
    - qt5-qttools
    - qt5-qttools-common
    - qt5-qttools-libs-designer
    - qt5-qttools-libs-designercomponents
    - qt5-qttools-libs-help
    - qt5-qttranslations
    - qt5-qtvirtualkeyboard
    - qt5-qtwayland
    - qt5-qtwebchannel
    - qt5-qtwebsockets
    - qt5-qtx11extras
    - qt5-qtxmlpatterns
    - rav1e-libs
    - readline
    - redhat-menus
    - rpm
    - rpm-libs
    - rpm-sequoia
    - rubberband-libs
    - samba-client-libs
    - samba-common
    - samba-common-libs
    - sdl2-compat
    - SDL2_image
    - SDL2_mixer
    - SDL2_net
    - SDL2_ttf
    - SDL3
    - SDL3_image
    - SDL3_ttf
    - sed
    - serd
    - setup
    - sgml-common
    - shadow-utils
    - shared-mime-info
    - signon-qt5
    - slang
    - snappy
    - sord
    - sound-theme-freedesktop
    - soundtouch
    - soxr
    - speech-dispatcher-libs
    - speex
    - speexdsp
    - spirv-tools-libs
    - sqlite-libs
    - sratom
    - srt-libs
    - svt-av1-libs
    - systemd-libs
    - systemd-standalone-sysusers
    - systemd-standalone-tmpfiles
    - taglib
    - tar
    - tcl
    - tesseract-common
    - tesseract-langpack-eng
    - tesseract-libs
    - tesseract-tessdata-doc
    - tk
    - tpm2-tss
    - turbojpeg
    - twolame-libs
    - tzdata
    - tzdata-java
    - unbound-libs
    - unzip
    - util-linux
    - util-linux-core
    - util-linux-script
    - vid.stab
    - vo-amrwbenc
    - vulkan-loader
    - wavpack
    - wcurl
    - webrtc-audio-processing
    - wget2
    - wget2-libs
    - wget2-wget
    - which
    - xcb-util
    - xcb-util-cursor
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xdg-user-dirs
    - xdg-utils
    - xevd-libs
    - xeve-libs
    - xkbcomp
    - xkeyboard-config
    - xml-common
    - xprop
    - xvidcore
    - xxhash-libs
    - xz
    - xz-libs
    - xz-lzma-compat
    - zeromq
    - zimg
    - zip
    - zix
    - zlib-ng
    - zlib-ng-compat
    - zstd
    - zvbi
    - zxing-cpp
  arch_packages:
    aarch64:
      - libhwasan
      - python3-qt5-webengine
      - qt5-qtwebengine
    ppc64le:
      - libquadmath
      - librtas
    x86_64:
      - libhwasan
      - libquadmath
      - libvmaf
      - libvpl
      - python3-qt5-webengine
      - qt5-qtwebengine
