document: feedback-pipeline-workload
version: 1
data:
  name: flatpak-runtime
  description: Fedora org.fedoraproject.Platform flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-runtime
  packages:
    - abattis-cantarell-vf-fonts
    - acl
    - adwaita-cursor-theme
    - adwaita-icon-theme
    - adwaita-icon-theme-legacy
    - adwaita-mono-fonts
    - adwaita-sans-fonts
    - alsa-lib
    - alsa-plugins-arcamav
    - alsa-plugins-oss
    - alsa-plugins-pulseaudio
    - alsa-plugins-upmix
    - alsa-plugins-usbstream
    - alsa-plugins-vdownmix
    - alternatives
    - appstream
    - aribb24
    - at-spi2-atk
    - at-spi2-core
    - atk
    - attr
    - audit-libs
    - authselect
    - authselect-libs
    - avahi-glib
    - avahi-libs
    - bash
    - bash-completion
    - bluez-libs
    - bsdcat
    - bsdcpio
    - bsdtar
    - bsdunzip
    - bubblewrap
    - bzip2
    - bzip2-libs
    - ca-certificates
    - cairo
    - cairo-gobject
    - cdparanoia-libs
    - cjson
    - cmake-filesystem
    - codec2
    - colord-libs
    - coreutils-single
    - cracklib
    - cracklib-dicts
    - crypto-policies
    - cups-client
    - cups-filesystem
    - cups-libs
    - curl
    - cyrus-sasl-gssapi
    - cyrus-sasl-lib
    - cyrus-sasl-md5
    - cyrus-sasl-plain
    - cyrus-sasl-scram
    - dbus
    - dbus-common
    - dbus-libs
    - dbus-tools
    - default-fonts-core-sans
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - desktop-file-utils
    - diffutils
    - double-conversion
    - duktape
    - e2fsprogs-libs
    - elfutils-debuginfod-client
    - elfutils-default-yama-scope
    - elfutils-libelf
    - elfutils-libs
    - emacs-filesystem
    - enchant2
    - expat
    - faad2-libs
    - fcitx5-gtk
    - fcitx5-gtk3
    - fcitx5-gtk4
    - fcitx5-qt6
    - fdk-aac-free
    - fedora-gpg-keys
    - fedora-release-common
    - fedora-release-flatpak
    - fedora-release-identity-flatpak
    - fedora-repos
    - ffmpeg-free
    - fftw-libs-double
    - fftw-libs-single
    - file
    - file-libs
    - filesystem
    - findutils
    - flac
    - flac-libs
    - flatpak-runtime-config
    - flatpak-spawn
    - flatpak-xdg-utils
    - flite
    - fmt
    - fontconfig
    - fonts-filesystem
    - freeglut
    - freetype
    - frei0r-plugins
    - fribidi
    - game-music-emu
    - gavl
    - gawk
    - gcr-libs
    - gdbm-libs
    - gdk-pixbuf2
    - geoclue2-libs
    - gettext
    - gettext-envsubst
    - gettext-libs
    - gettext-runtime
    - giflib
    - gjs
    - glib-networking
    - glib2
    - glibc
    - glibc-common
    - glibc-gconv-extra
    - glibc-langpack-*
    - glibc-minimal-langpack
    - glx-utils
    - glycin-gtk4-libs
    - glycin-libs
    - glycin-loaders
    - glycin-thumbnailer
    - gmp
    - gmp-c++
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - gnupg2
    - gnupg2-dirmngr
    - gnupg2-gpg-agent
    - gnupg2-gpgconf
    - gnupg2-keyboxd
    - gnupg2-scdaemon
    - gnupg2-smime
    - gnupg2-utils
    - gnupg2-verify
    - gnupg2-wks
    - gnutls
    - gnutls-c++
    - gnutls-dane
    - gnutls-utils
    - gobject-introspection
    - google-carlito-fonts
    - google-crosextra-caladea-fonts
    - google-noto-color-emoji-fonts
    - google-noto-fonts-common
    - google-noto-sans-mono-vf-fonts
    - google-noto-sans-vf-fonts
    - google-noto-serif-vf-fonts
    - gpgme
    - gpgmepp
    - graphene
    - graphite2
    - grep
    - gsettings-desktop-schemas
    - gsm
    - gssdp
    - gstreamer1
    - gstreamer1-plugin-dav1d
    - gstreamer1-plugin-gif
    - gstreamer1-plugin-gtk4
    - gstreamer1-plugin-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-libs
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-gtk
    - gtk-immodules-imsettings
    - gtk-update-icon-cache
    - gtk3
    - gtk3-immodule-xim
    - gtk3-immodules
    - gtk4
    - gtksourceview5
    - gupnp
    - gupnp-igd
    - gvfs-client
    - gzip
    - harfbuzz
    - harfbuzz-icu
    - hicolor-icon-theme
    - hidapi
    - highway
    - hiredis
    - hostname
    - hunspell
    - hunspell-??
    - hunspell-??-*
    - hunspell-???
    - hunspell-en-US
    - hunspell-filesystem
    - hwdata
    - hyphen
    - hyphen-??
    - hyphen-??-*
    - hyphen-???
    - ibus-gtk3
    - ibus-gtk4
    - ibus-libs
    - ilbc
    - iso-codes
    - jansson
    - javascriptcoregtk4.1
    - javascriptcoregtk6.0
    - jbigkit-libs
    - json-c
    - json-glib
    - keyutils-libs
    - krb5-libs
    - ladspa
    - lame
    - lame-libs
    - lcms2
    - leptonica
    - less
    - libacl
    - libadwaita
    - libaom
    - libappstream-glib
    - libarchive
    - libaribcaption
    - libasan
    - libass
    - libassuan
    - libasyncns
    - libatomic
    - libattr
    - libavc1394
    - libavcodec-free
    - libavdevice-free
    - libavfilter-free
    - libavformat-free
    - libavif
    - libavutil-free
    - libb2
    - libblkid
    - libbluray
    - libbrotli
    - libbs2b
    - libcaca
    - libcanberra
    - libcanberra-gtk3
    - libcap
    - libcap-ng
    - libcbor
    - libcdio
    - libcdio-paranoia
    - libchromaprint
    - libcloudproviders
    - libcom_err
    - libcurl
    - libdatrie
    - libdav1d
    - libdc1394
    - libdecor
    - libdex
    - libdovi
    - libdrm
    - libdvbv5
    - libdvdnav
    - libdvdread
    - libebur128
    - libeconf
    - libedit
    - libei
    - libeis
    - libepoxy
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - libevdev
    - libevent
    - libexif
    - libfdisk
    - libffi
    - libfido2
    - libfl2
    - libfontenc
    - libfyaml
    - libgcab1
    - libgcc
    - libgcrypt
    - libgdither
    - libgee
    - libgfortran
    - libglvnd
    - libglvnd-egl
    - libglvnd-gles
    - libglvnd-glx
    - libglvnd-opengl
    - libgomp
    - libgpg-error
    - libgudev
    - libgusb
    - libhandy
    - libheif
    - libheif-tools
    - libICE
    - libicu
    - libidn2
    - libiec61883
    - libinput
    - libitm
    - libjpeg-turbo
    - libjpeg-turbo-utils
    - libjxl
    - libkadm5
    - libksba
    - liblastlog2
    - liblc3
    - libldac
    - libldb
    - liblerc
    - liblsan
    - libmanette
    - libmodplug
    - libmount
    - libmysofa
    - libnghttp2
    - libnice
    - libnice-gstreamer1
    - libnotify
    - libnsl2
    - libobjc
    - liboeffis
    - libogg
    - libopenjph
    - libopenmpt
    - libpciaccess
    - libpkgconf
    - libplacebo
    - libpng
    - libpostproc-free
    - libproxy
    - libpsl
    - librabbitmq
    - libraw1394
    - librist
    - librsvg2
    - libsamplerate
    - libsbc
    - libseccomp
    - libsecret
    - libselinux
    - libsemanage
    - libsepol
    - libshaderc
    - libshout
    - libSM
    - libsmartcols
    - libsmbclient
    - libsndfile
    - libsodium
    - libsoup3
    - libsrtp
    - libss
    - libssh
    - libssh-config
    - libstdc++
    - libstemmer
    - libswresample-free
    - libswscale-free
    - libtalloc
    - libtasn1
    - libtdb
    - libtevent
    - libtextstyle
    - libthai
    - libtheora
    - libtiff
    - libtinysparql
    - libtirpc
    - libtommath
    - libtool-ltdl
    - libtsan
    - libubsan
    - libudfread
    - libunibreak
    - libunistring
    - libunwind
    - liburing
    - libusb1
    - libutempter
    - libuuid
    - libv4l
    - libva
    - libvdpau
    - libverto
    - libvisual
    - libvorbis
    - libvpx
    - libwacom
    - libwacom-data
    - libwayland-client
    - libwayland-cursor
    - libwayland-egl
    - libwayland-server
    - libwbclient
    - libwebp
    - libwebp-tools
    - libX11
    - libX11-common
    - libX11-xcb
    - libXau
    - libxcb
    - libXcomposite
    - libxcrypt
    - libXcursor
    - libXdamage
    - libXdmcp
    - libXext
    - libXfixes
    - libXft
    - libXi
    - libXinerama
    - libxkbcommon
    - libxkbcommon-x11
    - libxkbfile
    - libxml2
    - libxmlb
    - libXpm
    - libXrandr
    - libXrender
    - libXScrnSaver
    - libxshmfence
    - libxslt
    - libXtst
    - libXv
    - libXxf86vm
    - libyaml
    - libyuv
    - libzstd
    - lilv-libs
    - lmdb-libs
    - lpcnetfreedv
    - lua
    - lua-libs
    - lz4
    - lz4-libs
    - lzip
    - lzo
    - mailcap
    - mbedtls
    - mesa-filesystem
    - mesa-libgbm
    - mesa-libGLU
    - mkfontscale
    - mozjs140
    - mpdecimal
    - mpfr
    - mpg123-libs
    - mtdev
    - mythes
    - mythes-??
    - mythes-??-*
    - nano
    - ncompress
    - ncurses
    - ncurses-base
    - ncurses-libs
    - ncurses-term
    - nettle
    - ngtcp2
    - noopenh264
    - npth
    - nspr
    - nss
    - nss-softokn
    - nss-softokn-freebl
    - nss-sysinit
    - nss-util
    - nss_db
    - nss_hesiod
    - openal-soft
    - opencl-filesystem
    - OpenCL-ICD-Loader
    - opencore-amr
    - openjpeg
    - openjpeg-tools
    - openldap
    - openpgm
    - openssh
    - openssh-clients
    - openssl-libs
    - opus
    - opusfile
    - orc
    - p11-kit
    - p11-kit-client
    - p11-kit-trust
    - pam-libs
    - pango
    - pciutils-libs
    - pcre2
    - pcre2-syntax
    - pcre2-utf16
    - pcre2-utf32
    - pinentry
    - pinentry-gnome3
    - pipewire-alsa
    - pipewire-gstreamer
    - pipewire-jack-audio-connection-kit
    - pipewire-jack-audio-connection-kit-libs
    - pipewire-libs
    - pixman
    - pkcs11-provider
    - pkgconf
    - pkgconf-m4
    - pkgconf-pkg-config
    - plutosvg
    - plutovg
    - popt
    - procps-ng
    - protobuf-c
    - publicsuffix-list-dafsa
    - pulseaudio-libs
    - pulseaudio-libs-glib2
    - python-pip-wheel
    - python-unversioned-command
    - python3
    - python3-brotli
    - python3-cairo
    - python3-gobject
    - python3-gobject-base
    - python3-gstreamer1
    - python3-libs
    - python3-libxml2
    - python3-libxslt
    - python3-mako
    - python3-markdown
    - python3-markupsafe
    - python3-packaging
    - python3-setuptools
    - python3-tkinter
    - qrencode-libs
    - qt6-filesystem
    - qt6-qtbase
    - qt6-qtbase-common
    - qt6-qtbase-gui
    - qt6-qtdeclarative
    - qt6-qtsvg
    - qt6-qttranslations
    - qt6-qtwayland
    - rav1e-libs
    - readline
    - rpm
    - rpm-libs
    - rpm-sequoia
    - rubberband-libs
    - samba-client-libs
    - samba-common
    - samba-common-libs
    - sdl2-compat
    - SDL2_image
    - SDL2_mixer
    - SDL2_net
    - SDL2_ttf
    - SDL3
    - SDL3_image
    - SDL3_ttf
    - sed
    - serd
    - setup
    - sgml-common
    - shadow-utils
    - shared-mime-info
    - slang
    - snappy
    - sord
    - sound-theme-freedesktop
    - soundtouch
    - soxr
    - speech-dispatcher-libs
    - speex
    - speexdsp
    - spirv-tools-libs
    - sqlite-libs
    - sratom
    - srt-libs
    - svt-av1-libs
    - systemd-libs
    - systemd-standalone-sysusers
    - systemd-standalone-tmpfiles
    - taglib
    - tar
    - tcl
    - tesseract-common
    - tesseract-langpack-eng
    - tesseract-libs
    - tesseract-tessdata-doc
    - tk
    - tpm2-tss
    - tslib
    - turbojpeg
    - twolame-libs
    - tzdata
    - tzdata-java
    - unbound-libs
    - unzip
    - util-linux
    - util-linux-core
    - util-linux-script
    - vid.stab
    - vo-amrwbenc
    - vulkan-loader
    - wavpack
    - webkit2gtk4.1
    - webkitgtk6.0
    - webrtc-audio-processing
    - wget2
    - wget2-libs
    - wget2-wget
    - which
    - woff2
    - xcb-util
    - xcb-util-cursor
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xdg-dbus-proxy
    - xdg-user-dirs
    - xdg-utils
    - xevd-libs
    - xeve-libs
    - xkbcomp
    - xkeyboard-config
    - xml-common
    - xprop
    - xvidcore
    - xz
    - xz-libs
    - xz-lzma-compat
    - yelp
    - yelp-libs
    - yelp-xsl
    - zeromq
    - zimg
    - zip
    - zix
    - zlib-ng
    - zlib-ng-compat
    - zstd
    - zvbi
  arch_packages:
    aarch64:
      - libhwasan
    ppc64le:
      - libquadmath
      - librtas
    x86_64:
      - libhwasan
      - libquadmath
      - libvmaf
      - libvpl

