document: feedback-pipeline-workload
version: 1
data:
  name: flatpak-runtime-locale
  description: Fedora org.fedoraproject.Platform.Locale flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-runtime
  packages:
    - glibc-langpack-*
    - hunspell-??
    - hunspell-??-*
    - hunspell-???
    - hyphen-??
    - hyphen-??-*
    - hyphen-???
    - mythes-??
    - mythes-??-*
    - qt6-qttranslations
    - qt6-qtwebengine
    # for cleanup-commands (part of runtime)
    - coreutils-single
    - sed
