document: feedback-pipeline-workload
version: 1
data:
  name: flatpak-kde6-runtime
  description: Fedora org.fedoraproject.KDE6Platform flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-runtime
  packages:
    - abattis-cantarell-vf-fonts
    - abseil-cpp
    - accounts-qml-module-qt6
    - acl
    - adwaita-cursor-theme
    - adwaita-icon-theme
    - adwaita-icon-theme-legacy
    - alsa-lib
    - alsa-plugins-arcamav
    - alsa-plugins-oss
    - alsa-plugins-pulseaudio
    - alsa-plugins-upmix
    - alsa-plugins-usbstream
    - alsa-plugins-vdownmix
    - alternatives
    - appstream
    - appstream-qt
    - aribb24
    - assimp
    - at-spi2-atk
    - at-spi2-core
    - atk
    - attr
    - audit-libs
    - authselect
    - authselect-libs
    - avahi-glib
    - avahi-libs
    - bash
    - bash-completion
    - bluez-libs
    - breeze-cursor-theme
    - breeze-icon-theme
    - bsdcat
    - bsdcpio
    - bsdtar
    - bsdunzip
    - bubblewrap
    - bzip2
    - bzip2-libs
    - ca-certificates
    - cairo
    - cairo-gobject
    - cdparanoia-libs
    - cjson
    - cmake-filesystem
    - codec2
    - colord-libs
    - coreutils-single
    - cracklib
    - cracklib-dicts
    - crypto-policies
    - cups-client
    - cups-filesystem
    - cups-libs
    - curl
    - cyrus-sasl-gssapi
    - cyrus-sasl-lib
    - cyrus-sasl-md5
    - cyrus-sasl-plain
    - cyrus-sasl-scram
    - dbus
    - dbus-common
    - dbus-libs
    - dbus-tools
    - default-fonts-core-sans
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - desktop-file-utils
    - diffutils
    - dns-root-data
    - docbook-dtds
    - docbook-style-xsl
    - double-conversion
    - duktape
    - e2fsprogs-libs
    - ebook-tools-libs
    - editorconfig-libs
    - elfutils-debuginfod-client
    - elfutils-default-yama-scope
    - elfutils-libelf
    - elfutils-libs
    - emacs-filesystem
    - enchant2
    - exiv2-libs
    - expat
    - faad2-libs
    - fcitx5-gtk
    - fcitx5-gtk3
    - fcitx5-qt6
    - fdk-aac-free
    - fedora-gpg-keys
    - fedora-logos
    - fedora-release-common
    - fedora-release-flatpak
    - fedora-release-identity-flatpak
    - fedora-repos
    - ffmpeg-free
    - fftw-libs-double
    - fftw-libs-single
    - file
    - file-libs
    - filesystem
    - findutils
    - flac
    - flac-libs
    - flatpak-runtime-config
    - flatpak-spawn
    - flatpak-xdg-utils
    - flite
    - fmt
    - fontconfig
    - fonts-filesystem
    - freeglut
    - freetype
    - frei0r-plugins
    - fribidi
    - game-music-emu
    - gavl
    - gawk
    - gcr-libs
    - gdbm-libs
    - gdk-pixbuf2
    - geoclue2-libs
    - gettext
    - gettext-envsubst
    - gettext-libs
    - gettext-runtime
    - giflib
    - glib-networking
    - glib2
    - glibc
    - glibc-common
    - glibc-gconv-extra
    - glibc-langpack-*
    - glibc-minimal-langpack
    - glx-utils
    - glycin-libs
    - glycin-loaders
    - gmp
    - gmp-c++
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - gnupg2
    - gnupg2-dirmngr
    - gnupg2-gpg-agent
    - gnupg2-gpgconf
    - gnupg2-keyboxd
    - gnupg2-scdaemon
    - gnupg2-smime
    - gnupg2-utils
    - gnupg2-verify
    - gnupg2-wks
    - gnutls
    - gnutls-c++
    - gnutls-dane
    - gnutls-utils
    - gobject-introspection
    - google-carlito-fonts
    - google-crosextra-caladea-fonts
    - google-noto-color-emoji-fonts
    - google-noto-fonts-common
    - google-noto-sans-mono-vf-fonts
    - google-noto-sans-vf-fonts
    - google-noto-serif-vf-fonts
    - gpgme
    - gpgmepp
    - graphene
    - graphite2
    - grep
    - gsettings-desktop-schemas
    - gsm
    - gssdp
    - gstreamer1
    - gstreamer1-plugin-dav1d
    - gstreamer1-plugin-gif
    - gstreamer1-plugin-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-libs
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-gtk
    - gstreamer1-plugins-good-qt6
    - gtk-immodules-imsettings
    - gtk-update-icon-cache
    - gtk3
    - gtk3-immodule-xim
    - gtk3-immodules
    - gupnp
    - gupnp-igd
    - gzip
    - harfbuzz
    - harfbuzz-icu
    - hicolor-icon-theme
    - highway
    - hiredis
    - hostname
    - hunspell
    - hunspell-??
    - hunspell-??-*
    - hunspell-???
    - hunspell-en-US
    - hunspell-filesystem
    - hwdata
    - hyphen
    - hyphen-??
    - hyphen-??-*
    - hyphen-???
    - ibus-gtk3
    - ibus-libs
    - ilbc
    - imath
    - inih
    - inih-cpp
    - iso-codes
    - jansson
    - jasper-libs
    - jbigkit-libs
    - json-c
    - json-glib
    - jsoncpp
    - jxrlib
    - kaccounts-integration-qt6
    - kde-filesystem
    - kde-settings
    - kdecoration
    - kdegraphics-mobipocket
    - kdsoap-ws-discovery-client
    - kdsoap6
    - keyutils-libs
    - kf6-attica
    - kf6-bluez-qt
    - kf6-breeze-icons
    - kf6-filesystem
    - kf6-frameworkintegration
    - kf6-frameworkintegration-libs
    - kf6-karchive
    - kf6-kauth
    - kf6-kbookmarks
    - kf6-kcalendarcore
    - kf6-kcmutils
    - kf6-kcodecs
    - kf6-kcolorscheme
    - kf6-kcompletion
    - kf6-kconfig
    - kf6-kconfigwidgets
    - kf6-kcontacts
    - kf6-kcoreaddons
    - kf6-kcrash
    - kf6-kdav
    - kf6-kdbusaddons
    - kf6-kdeclarative
    - kf6-kded
    - kf6-kdnssd
    - kf6-kdoctools
    - kf6-kfilemetadata
    - kf6-kglobalaccel
    - kf6-kguiaddons
    - kf6-kholidays
    - kf6-ki18n
    - kf6-kiconthemes
    - kf6-kidletime
    - kf6-kidletime-x11
    - kf6-kimageformats
    - kf6-kio-core
    - kf6-kio-core-libs
    - kf6-kio-doc
    - kf6-kio-file-widgets
    - kf6-kio-gui
    - kf6-kio-widgets
    - kf6-kio-widgets-libs
    - kf6-kirigami
    - kf6-kirigami-addons
    - kf6-kitemmodels
    - kf6-kitemviews
    - kf6-kjobwidgets
    - kf6-knewstuff
    - kf6-knotifications
    - kf6-knotifyconfig
    - kf6-kpackage
    - kf6-kparts
    - kf6-kplotting
    - kf6-kpty
    - kf6-kquickcharts
    - kf6-kservice
    - kf6-kstatusnotifieritem
    - kf6-ksvg
    - kf6-ktexteditor
    - kf6-ktexttemplate
    - kf6-ktextwidgets
    - kf6-kunitconversion
    - kf6-kwallet
    - kf6-kwallet-libs
    - kf6-kwidgetsaddons
    - kf6-kwindowsystem
    - kf6-kxmlgui
    - kf6-prison
    - kf6-purpose
    - kf6-qqc2-desktop-style
    - kf6-solid
    - kf6-sonnet
    - kf6-sonnet-hunspell
    - kf6-syndication
    - kf6-syntax-highlighting
    - kf6-threadweaver
    - kio-extras
    - krb5-libs
    - kwayland
    - ladspa
    - lame
    - lame-libs
    - lcms2
    - leptonica
    - less
    - libaccounts-glib
    - libaccounts-qt6
    - libacl
    - libaom
    - libappstream-glib
    - libarchive
    - libaribcaption
    - libasan
    - libass
    - libassuan
    - libasyncns
    - libatomic
    - libattr
    - libavc1394
    - libavcodec-free
    - libavdevice-free
    - libavfilter-free
    - libavformat-free
    - libavif
    - libavutil-free
    - libb2
    - libblkid
    - libbluray
    - libbrotli
    - libbs2b
    - libcaca
    - libcanberra
    - libcanberra-gtk3
    - libcap
    - libcap-ng
    - libcbor
    - libcdio
    - libcdio-paranoia
    - libchromaprint
    - libcloudproviders
    - libcom_err
    - libcurl
    - libdatrie
    - libdav1d
    - libdc1394
    - libdecor
    - libdeflate
    - libdmtx
    - libdovi
    - libdrm
    - libdvbv5
    - libdvdnav
    - libdvdread
    - libebur128
    - libeconf
    - libedit
    - libepoxy
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - libevdev
    - libevent
    - libexif
    - libfdisk
    - libffi
    - libfido2
    - libfl2
    - libfontenc
    - libfyaml
    - libgcab1
    - libgcc
    - libgcrypt
    - libgdither
    - libgfortran
    - libglvnd
    - libglvnd-egl
    - libglvnd-gles
    - libglvnd-glx
    - libglvnd-opengl
    - libgomp
    - libgpg-error
    - libgudev
    - libgusb
    - libheif
    - libical
    - libICE
    - libicu
    - libidn2
    - libiec61883
    - libimobiledevice
    - libimobiledevice-glue
    - libinput
    - libitm
    - libjpeg-turbo
    - libjpeg-turbo-utils
    - libjxl
    - libkexiv2-qt6
    - libksba
    - liblastlog2
    - liblc3
    - libldac
    - libldb
    - liblerc
    - liblsan
    - libmng
    - libmodplug
    - libmount
    - libmtp
    - libmysofa
    - libnghttp2
    - libnice
    - libnice-gstreamer1
    - libnotify
    - libnsl2
    - libobjc
    - libogg
    - libopenjph
    - libopenmpt
    - libpciaccess
    - libpkgconf
    - libplacebo
    - libplist
    - libpng
    - libpostproc-free
    - libproxy
    - libpsl
    - librabbitmq
    - LibRaw
    - libraw1394
    - librist
    - librsvg2
    - libsamplerate
    - libsbc
    - libseccomp
    - libsecret
    - libselinux
    - libsemanage
    - libsepol
    - libshaderc
    - libshout
    - libSM
    - libsmartcols
    - libsmbclient
    - libsndfile
    - libsodium
    - libsoup3
    - libsrtp
    - libss
    - libssh
    - libssh-config
    - libstdc++
    - libstemmer
    - libswresample-free
    - libswscale-free
    - libtalloc
    - libtasn1
    - libtdb
    - libtevent
    - libtextstyle
    - libthai
    - libtheora
    - libtiff
    - libtinysparql
    - libtirpc
    - libtommath
    - libtool-ltdl
    - libtsan
    - libubsan
    - libudfread
    - libunibreak
    - libunistring
    - libunwind
    - libusb1
    - libusbmuxd
    - libutempter
    - libuuid
    - libv4l
    - libva
    - libvdpau
    - libverto
    - libvisual
    - libvorbis
    - libvpx
    - libwacom
    - libwacom-data
    - libwayland-client
    - libwayland-cursor
    - libwayland-egl
    - libwayland-server
    - libwbclient
    - libwebp
    - libwebp-tools
    - libX11
    - libX11-common
    - libX11-xcb
    - libXau
    - libxcb
    - libXcomposite
    - libxcrypt
    - libXcursor
    - libXdamage
    - libXdmcp
    - libXext
    - libXfixes
    - libXft
    - libXi
    - libXinerama
    - libxkbcommon
    - libxkbcommon-x11
    - libxkbfile
    - libxml2
    - libxmlb
    - libXpm
    - libXrandr
    - libXrender
    - libXScrnSaver
    - libxshmfence
    - libxslt
    - libXtst
    - libXv
    - libXxf86vm
    - libyaml
    - libyuv
    - libzip
    - libzstd
    - lilv-libs
    - lmdb-libs
    - lpcnetfreedv
    - lua
    - lua-libs
    - lz4
    - lz4-libs
    - lzip
    - lzo
    - mailcap
    - mbedtls
    - mesa-filesystem
    - mesa-libgbm
    - mesa-libGLU
    - minizip-ng-compat
    - mkfontscale
    - mpdecimal
    - mpfr
    - mpg123-libs
    - mtdev
    - mythes
    - mythes-??
    - mythes-??-*
    - nano
    - ncompress
    - ncurses
    - ncurses-base
    - ncurses-libs
    - ncurses-term
    - nettle
    - ngtcp2
    - ngtcp2-crypto-gnutls
    - ngtcp2-crypto-ossl
    - noopenh264
    - npth
    - nspr
    - nss
    - nss-mdns
    - nss-softokn
    - nss-softokn-freebl
    - nss-sysinit
    - nss-util
    - nss_db
    - nss_hesiod
    - openal-soft
    - opencl-filesystem
    - OpenCL-ICD-Loader
    - opencore-amr
    - openexr-libs
    - openjpeg
    - openjpeg-tools
    - openldap
    - openpgm
    - openssh
    - openssh-clients
    - openssh-keysign
    - openssl-libs
    - openxr-libs
    - opus
    - opusfile
    - orc
    - p11-kit
    - p11-kit-client
    - p11-kit-trust
    - PackageKit-Qt6
    - pam-libs
    - pango
    - pciutils-libs
    - pcre2
    - pcre2-syntax
    - pcre2-utf16
    - pcre2-utf32
    - phonon-common
    - phonon-qt6
    - pinentry
    - pinentry-gnome3
    - pinentry-qt
    - pipewire-alsa
    - pipewire-gstreamer
    - pipewire-jack-audio-connection-kit
    - pipewire-jack-audio-connection-kit-libs
    - pipewire-libs
    - pixman
    - pkcs11-provider
    - pkgconf
    - pkgconf-m4
    - pkgconf-pkg-config
    - plasma-activities
    - plasma-activities-stats
    - plasma-breeze
    - plasma-breeze-common
    - plasma-breeze-qt6
    - plasma-integration
    - plutosvg
    - plutovg
    - polkit-libs
    - polkit-qt6-1
    - poly2tri
    - poppler
    - poppler-data
    - poppler-glib
    - poppler-qt6
    - popt
    - procps-ng
    - protobuf-c
    - publicsuffix-list-dafsa
    - pugixml
    - pulseaudio-libs
    - pulseaudio-libs-glib2
    - python-pip-wheel
    - python-pyqt6-rpm-macros
    - python-unversioned-command
    - python3
    - python3-brotli
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python3-gobject-base
    - python3-gpg
    - python3-libs
    - python3-libxml2
    - python3-libxslt
    - python3-mako
    - python3-markdown
    - python3-markupsafe
    - python3-packaging
    - python3-pyqt6
    - python3-pyqt6-base
    - python3-pyqt6-charts
    - python3-pyqt6-sip
    - python3-setuptools
    - python3-six
    - python3-tkinter
    - qca-qt6
    - qca-qt6-cyrus-sasl
    - qca-qt6-gnupg
    - qca-qt6-logger
    - qca-qt6-nss
    - qca-qt6-ossl
    - qca-qt6-softstore
    - qgpgme-qt6
    - qqc2-breeze-style
    - qrencode-libs
    - qt6-filesystem
    - qt6-qt3d
    - qt6-qt5compat
    - qt6-qtbase
    - qt6-qtbase-common
    - qt6-qtbase-gui
    - qt6-qtcharts
    - qt6-qtconnectivity
    - qt6-qtdeclarative
    - qt6-qthttpserver
    - qt6-qtimageformats
    - qt6-qtlocation
    - qt6-qtmultimedia
    - qt6-qtnetworkauth
    - qt6-qtpositioning
    - qt6-qtquick3d
    - qt6-qtquicktimeline
    - qt6-qtremoteobjects
    - qt6-qtscxml
    - qt6-qtsensors
    - qt6-qtserialport
    - qt6-qtshadertools
    - qt6-qtspeech
    - qt6-qtspeech-flite
    - qt6-qtspeech-speechd
    - qt6-qtsvg
    - qt6-qttools
    - qt6-qttools-common
    - qt6-qttools-libs-designer
    - qt6-qttools-libs-designercomponents
    - qt6-qttools-libs-help
    - qt6-qttranslations
    - qt6-qtvirtualkeyboard
    - qt6-qtwayland
    - qt6-qtwebchannel
    - qt6-qtwebsockets
    - rav1e-libs
    - re2
    - readline
    - redhat-menus
    - rpm
    - rpm-libs
    - rpm-sequoia
    - rubberband-libs
    - samba-client-libs
    - samba-common
    - samba-common-libs
    - sdl2-compat
    - SDL2_image
    - SDL2_mixer
    - SDL2_net
    - SDL2_ttf
    - SDL3
    - SDL3_image
    - SDL3_ttf
    - sed
    - serd
    - setup
    - sgml-common
    - shadow-utils
    - shared-mime-info
    - signon-qt6
    - slang
    - snappy
    - sord
    - sound-theme-freedesktop
    - soundtouch
    - soxr
    - speech-dispatcher-libs
    - speex
    - speexdsp
    - spirv-tools-libs
    - sqlite-libs
    - sratom
    - srt-libs
    - svt-av1-libs
    - systemd-libs
    - systemd-standalone-sysusers
    - systemd-standalone-tmpfiles
    - taglib
    - tar
    - tcl
    - tesseract-common
    - tesseract-langpack-eng
    - tesseract-libs
    - tesseract-tessdata-doc
    - tk
    - tpm2-tss
    - tslib
    - turbojpeg
    - twolame-libs
    - tzdata
    - tzdata-java
    - unbound-libs
    - unzip
    - util-linux
    - util-linux-core
    - util-linux-script
    - vid.stab
    - vo-amrwbenc
    - vulkan-loader
    - wavpack
    - webrtc-audio-processing
    - wget2
    - wget2-libs
    - wget2-wget
    - which
    - xcb-util
    - xcb-util-cursor
    - xcb-util-image
    - xcb-util-keysyms
    - xcb-util-renderutil
    - xcb-util-wm
    - xdg-user-dirs
    - xdg-utils
    - xevd-libs
    - xeve-libs
    - xkbcomp
    - xkeyboard-config
    - xml-common
    - xprop
    - xvidcore
    - xxhash-libs
    - xz
    - xz-libs
    - xz-lzma-compat
    - zeromq
    - zimg
    - zip
    - zix
    - zlib-ng
    - zlib-ng-compat
    - zstd
    - zvbi
    - zxing-cpp
  arch_packages:
    aarch64:
      - libhwasan
      - python3-pyqt6-webengine
      - qt6-qtpdf
      - qt6-qtquick3dphysics
      - qt6-qtwebengine
    ppc64le:
      - libquadmath
      - librtas
      - python3-pyqt6-webengine
      - qt6-qtpdf
      - qt6-qtwebengine
    x86_64:
      - libhwasan
      - libquadmath
      - libvmaf
      - libvpl
      - python3-pyqt6-webengine
      - qt6-qtpdf
      - qt6-qtquick3dphysics
      - qt6-qtwebengine
