document: feedback-pipeline-workload
version: 1
data:
  name: francis
  description: Fedora org.kde.francis flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - francis
