document: feedback-pipeline-workload
version: 1
data:
  name: intel-media-driver-free
  description: Fedora org.fedoraproject.Platform.VAAPI.Intel flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-runtime
  packages: []
  arch_packages:
    x86_64:
      - libva-intel-media-driver
      - intel-mediasdk
      - intel-vpl-gpu-rt
      # basic dependencies
      - intel-gmmlib
      - libigfxcmrt
      # for cleanup-commands (part of runtime)
      - coreutils-single
      - sed
