document: feedback-pipeline-workload
version: 1
data:
  name: keepsecret
  description: Fedora org.kde.keepsecret flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - keepsecret
