document: feedback-pipeline-workload
version: 1
data:
  name: klettres
  description: Fedora org.kde.klettres flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - klettres
