document: feedback-pipeline-workload
version: 1
data:
  name: llvm20
  description: Fedora org.fedoraproject.Sdk.Extension.llvm20 flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-sdk
  packages:
    - clang20
    - clang20-analyzer
    - clang20-devel
    - clang20-libs
    - clang20-tools-extra
    - clang20-tools-extra-devel
    - compiler-rt20
    - git-clang-format20
    - libcxx
    - libcxx-devel
    - libcxxabi
    - libcxxabi-devel
    - libomp20
    - libomp20-devel
    - lld20
    - lld20-devel
    - lld20-libs
    - lldb20
    - lldb20-devel
    - llvm20
    - llvm20-cmake-utils
    - llvm20-devel
    - llvm20-googletest
    - llvm20-libs
    - llvm-libunwind
    - llvm-libunwind-devel
    - llvm20-test
    - python3-clang
    - python3-lit
    - python3-lldb
    - llvm20-flatpak-config
    # for cleanup-commands (part of runtime)
    - coreutils-single
    - rpm
    - sed
