document: feedback-pipeline-workload
version: 1
data:
  name: mesa
  description: Fedora org.fedoraproject.Platform.GL.default flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-runtime
  packages:
    - mesa-libEGL
    - mesa-libGL
    - mesa-dri-drivers
    - mesa-va-drivers
    - mesa-vdpau-drivers
    - mesa-vulkan-drivers
    - mesa-flatpak-config
    # basic dependencies
    - libdrm
    - lm_sensors-libs
    # for cleanup-commands (part of runtime)
    - coreutils-single
    - sed
