document: feedback-pipeline-workload
version: 1
data:
  name: Pencil2D
  description: Fedora org.pencil2d.Pencil2D flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - Pencil2D
