document: feedback-pipeline-workload
version: 1
data:
  name: pidgin
  description: Fedora im.pidgin.Pidgin flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - pidgin
    - pidgin-birthday-reminder
    #- pidgin-chime
    - pidgin-indicator
    - pidgin-libnotify
    - pidgin-otr
    #- pidgin-sipe
    - pidgin-window-merge
    - purple-googlechat
    - purple-mm-sms
    - gtk2-flatpak-config
