document: feedback-pipeline-workload
version: 1
data:
  name: qpdfview
  description: Fedora net.launchpad.qpdfview flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - qpdfview
