document: feedback-pipeline-workload
version: 1
data:
  name: siril
  description: Fedora org.siril.Siril flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - siril
    - python3-astropy-healpix
