document: feedback-pipeline-workload
version: 1
data:
  name: sqlitebrowser
  description: Fedora org.sqlitebrowser.sqlitebrowser flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - sqlitebrowser
