document: feedback-pipeline-workload
version: 1
data:
  name: strawberry
  description: Fedora org.strawberrymusicplayer.strawberry flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - strawberry
