document: feedback-pipeline-workload
version: 1
data:
  name: torbrowser-launcher
  description: Fedora org.torproject.torbrowser-launcher flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages: []
  arch_packages:
    x86_64:
      - torbrowser-launcher
