document: feedback-pipeline-workload
version: 1
data:
  name: warzone2100
  description: Fedora net.wz2100.warzone2100 flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - warzone2100
    - warzone2100-sequences
